repositories: []

releases:
  - name: proconnect-carte-agent
    version: {{ .Values.version }}
    namespace: {{ .Namespace }}
    chart: ./proconnect-carte-agent
    values:
      - env.d/{{ .Environment.Name }}/values.yaml.gotmpl
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml

environments:
  dev:
    values:
      - version: 0.0.1
  staging:
    values:
      - version: 0.0.1
  outscale-production:
    values:
      - version: 0.0.1

