{{- if .Values.ingress.enabled -}}
{{- $fullName := include "proconnect-carte-agent.fullname" . -}}
{{- $port := .Values.app.service.port -}}
{{- $namespace := .Release.Namespace -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace | quote }}
  labels:
    {{- include "proconnect-carte-agent.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional"
    nginx.ingress.kubernetes.io/auth-tls-secret: {{ $namespace }}/proconnect-carte-agent-ca
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- if .Values.ingress.host }}
    - secretName: {{ $fullName }}-tls
      hosts:
        - {{ .Values.ingress.host | quote }}
    {{- end }}
    {{- range .Values.ingress.tls.additional }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}-app
                port:
                  number: {{ $port }}
          {{- end }}
          {{- with .Values.ingress.customBackends }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
    {{- end }}
{{- end }}

