const https = require('https');
const fs = require('fs');
const path = require('path');
const express = require('express');
const util = require('util');

// Initialize Express
const app = express();
const PORT = process.env.PORT || 3000;
const HOST = process.env.HOST || '0.0.0.0';

// Read certificates generated by mkcert
const serverOptions = {
  key: process.env.SERVER_KEY,
  cert: process.env.SERVER_CERT,
  ca: process.env.SERVER_CA,
  enableTrace: process.env.SERVER_TLS_TRACE == "true",

  // Request client certificate
  requestCert: true,
  secureOptions: require('constants').SSL_OP_NO_TLSv1_3, // Try disabling TLS 1.3

  rejectUnauthorized: false // Node default is rejectUnauthorized==true
};

// Basic API endpoint
app.get('/', (req, res) => {
  // Get client certificate information
  const clientCert = req.socket.getPeerCertificate(true);

  if (clientCert?.subject) {
    console.log('Client connected with certificate:');
    console.log(`- Subject: ${JSON.stringify(clientCert.subject)}`);
    console.log(`- Issuer: ${JSON.stringify(clientCert.issuer)}`);
    console.log(`- Valid from: ${clientCert.valid_from}`);
    console.log(`- Valid to: ${clientCert.valid_to}`);

    res.json({
      message: 'mTLS Authentication Successful!',
      clientCertificate: {
        subject: clientCert.subject,
        issuer: clientCert.issuer,
        validFrom: clientCert.valid_from,
        validTo: clientCert.valid_to
      }
    });
  } else {
    console.log('Client connected without certificate');
    res.status(401).json({ message: 'Client certificate required' });
  }
});

app.get('/ping', (req, res) => {
  res.status(200).send('OK');
});

// Create the HTTPS server with Express
const server = https.createServer(serverOptions, app);

server.on('connection', (socket) => {
  console.log(`New connection established from ${socket.remoteAddress}:${socket.remotePort}`);
});

server.on('secureConnection', (socket) => {
  console.log(`Secure connection established from ${socket.remoteAddress}:${socket.remotePort}`);
  console.log(`  Authorized: ${socket.authorized} (${socket.authorizationError})`);
});

server.on('tlsClientError', (err, socket) => {
  console.error('TLS client error:', err);
});

server.on('error', (err) => {
  console.error('Server error:', err);
});

// Start the server
server.listen(PORT, HOST, () => {
  console.log(`mTLS server running at https://${HOST}:${PORT}/`);
});
